### ISSUE TITLE
onItemSwitch fires with resize

### ISSUE THREAD

**Issue by billyrennekamp** [drien/jquery-flipster#35] opened 2014-08-21 16:55 UTC
is that intended? shouldn't it be a different callback like onResize?
is there a way to detect the difference?

**Comment by drien** [comment] 2015-03-10 03:33
This isn't supposed to be happening, I see where the issue is and I'll try to correct it for the next release.

**Comment by drien** [comment] 2015-03-18 04:53
Fixed in the v0.4 branch, which will be released with a bunch of other updates!

**Closed by drien** 2015-03-18 04:53 UTC
