### ISSUE TITLE
navigation children have incorrect active class bug

### ISSUE THREAD

**Issue by DrizzlyOwl** [drien/jquery-flipster#63] opened 2015-11-02 13:59 UTC
All children of `.flipster__nav` seem to have the class `flipster__nav__item--current` applied to them even if they are not currently selected.

My config is:
```javascript
flipContainer.flipster({
	itemContainer: flipItemContainer,
	itemSelector: flipItem,
	loop: true,
	autoplay: 3000,
	style: 'flat',
	spacing: -0.2,
	scrollwheel: false,
	nav: 'after',
	buttons: false,
})
```

Resulting HTML:
```html
[...]
<ul class="flipster__nav" role="navigation">
    <li class="flipster__nav__item flipster__nav__item--current">
        <a href="#" class="flipster__nav__link">0</a>
    </li>
    <li class="flipster__nav__item flipster__nav__item--current">
        <a href="#" class="flipster__nav__link">1</a>
    </li>
    <li class="flipster__nav__item flipster__nav__item--current">
        <a href="#" class="flipster__nav__link">2</a>
    </li>
    [...]
</ul>
```

**Comment by shshaw** [comment] 2015-11-02 15:12
I've attempted to recreate the issue, but I'm not getting the same results. 
http://codepen.io/shshaw/pen/JYBKPZ

Can you fork it to be more like your setup, or find a way to recreate the bug?

**Comment by DrizzlyOwl** [comment] 2015-11-02 15:23
As requested - forked and modified to be as close as possible to my setup.
http://codepen.io/DrizzlyOwl/pen/YyjWyg?editors=101

**Comment by shshaw** [comment] 2015-11-02 16:14
Ah yes. I do see that. Not sure of the cause... I'll have to dig into the nav code a bit more to debug. Thanks for pointing this out!

**Comment by DrizzlyOwl** [comment] 2015-11-02 16:32
I believe it's caused by `updateNav()` as I can see when a transition starts the classes are removed and then re-added once the transition stops. I think there needs to be an index check before adding the class

**Comment by shshaw** [comment] 2015-11-02 16:35
The index is checked in the [`filter` call](https://github.com/drien/jquery-flipster/blob/master/src/jquery.flipster.js#L296), but I believe the check for the nonexistant `data('category')` is causing it to return `true` when the index check fails.

**Comment by shshaw** [comment] 2015-11-02 16:37
Ah yes, that's it. Adding a check to see if the `category` variable is set fixes it. I'll do a little more testing and push a fix, but you can see it working here http://codepen.io/shshaw/pen/JYBKBz?editors=001

**Comment by shshaw** [comment] 2015-11-02 16:44
Should be good to go now. Download the latest version and test again in your project. If you run into any other issues, please let us know!

**Closed by shshaw** 2015-11-02 16:44 UTC
