### ISSUE TITLE
Artifacts on the last slide with Firefox

### ISSUE THREAD

**Issue by ghost** [drien/jquery-flipster#76] opened 2016-02-10 10:16 UTC
Hi,

I'm having artifacts on every style except the wheel. They appear when I slide to the last div.

Here's an example with the demo: http://i.imgur.com/7tyqf54.png

Disappears when scrolled through the page.

My user agent : Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:44.0) Gecko/20100101 Firefox/44.0

Regards.

**Comment by slavjon** [comment] 2016-02-16 15:48
Hello, i have this problem too in FF 44.0.2 Win 10 Pro
![2016-02-16_174302](https://cloud.githubusercontent.com/assets/17275281/13081431/7fc408a4-d4d5-11e5-86d2-7dac442a6cbe.png)

**Comment by shshaw** [comment] 2016-02-16 16:15
Very strange. I tested all of the themes on [my demo template](http://codepen.io/shshaw/pen/qOJWxR) in Firefox 43 & 44 on OS X with no problems. This might be a Windows specific issue. Can you try replicating this on the [demo template](http://codepen.io/shshaw/pen/qOJWxR) to help isolate any other factors?

**Comment by halesk** [comment] 2016-02-16 16:19
Same problem. Anything we can do to help?

**Comment by drien** [comment] 2016-02-16 16:24
I'll take a look from a Windows machine as soon as I get a chance.

**Comment by shshaw** [comment] 2016-02-16 16:44
I am able to replicate this using CrossBrowserTesting.com to run Windows 10. 

The issue is occurring on Firefox 41-44, at least, but does not occur in Chrome.

This is likely GPU related, since it's occurring on the 3D transform themes and not the flat `wheel` transform theme.

**Comment by shshaw** [comment] 2016-02-16 16:53
Simply adding a transparent outline seems to prevent the artifacting. I assume this is like the old `zoom` CSS trick for IE that would ensure elements rendered properly.

```
.flipster__item { outline: solid 1px transparent; }
```
[Updated Demo](http://codepen.io/shshaw/pen/MKxMdb)

This temporary fix should work while we dig further into this issue.

**Comment by shshaw** [comment] 2016-02-16 17:01
Feel free to contribute by seeing if this is a documented issue anywhere else, and if there are any stylesheet adjustments we can make (other than the outline hack) to resolve the issue. It seems to be strictly related to Firefox's handling of 3D transforms and transitions/animations. I found some old Mozilla bugtracker references to similar issues, but those were all apparently resolved in 2011/2012.

**Comment by slavjon** [comment] 2016-02-17 08:35
> Very strange. I tested all of the themes on my demo template in Firefox 43 & 44 on OS X with no problems. This might be a Windows specific issue. Can you try replicating this on the demo template to help isolate any other factors?

![2016-02-17_103437](https://cloud.githubusercontent.com/assets/17275281/13103848/29eebcf2-d562-11e5-8004-5262f7e37e4c.png)

**Comment by slavjon** [comment] 2016-02-17 08:37
.flipster__item { outline: solid 1px transparent; } 
it work!!

**Comment by Julie1082** [comment] 2019-02-22 10:07
Hi! Unfortunately, it didn't help in my case:
![image](https://user-images.githubusercontent.com/25283020/53235405-67738c00-369a-11e9-8442-e4c7e4d8b8e5.png)

**Comment by Julie1082** [comment] 2019-02-22 10:46
Problem was in filter: blur

**Comment by drien** [comment] 2024-01-18 00:25
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy

**Closed by drien** 2024-01-18 00:25 UTC
